# Generated by Django 5.1.2 on 2024-10-23 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the post', max_length=100, verbose_name='Title')),
                ('body', models.TextField(help_text='Enter the text', verbose_name='Body')),
                ('preview', models.ImageField(blank=True, help_text='Add a photo', null=True, upload_to='blog/photo', verbose_name='Photo')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Publication date')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
